// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3a-VfPzY-7DpIpIYSPkBkM-HrGzgnqNs',
    appId: '1:404562850809:web:c8bf8542a97fb2e9cd4328',
    messagingSenderId: '404562850809',
    projectId: 'openlibrary-92d68',
    authDomain: 'openlibrary-92d68.firebaseapp.com',
    storageBucket: 'openlibrary-92d68.appspot.com',
    measurementId: 'G-MP7V6E1G1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhQ0CoBfF8cihxEoWBogdPHnHbh8A4BQ0',
    appId: '1:404562850809:android:85b2ebae7d5d2517cd4328',
    messagingSenderId: '404562850809',
    projectId: 'openlibrary-92d68',
    storageBucket: 'openlibrary-92d68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEOq_3485zVtKMaFx-Y-zDvyfqIB9CBBc',
    appId: '1:404562850809:ios:128bccd0521bbff6cd4328',
    messagingSenderId: '404562850809',
    projectId: 'openlibrary-92d68',
    storageBucket: 'openlibrary-92d68.appspot.com',
    iosBundleId: 'com.ronaldjjingo.openlibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEOq_3485zVtKMaFx-Y-zDvyfqIB9CBBc',
    appId: '1:404562850809:ios:f761792174ec0c6acd4328',
    messagingSenderId: '404562850809',
    projectId: 'openlibrary-92d68',
    storageBucket: 'openlibrary-92d68.appspot.com',
    iosBundleId: 'com.example.openlibrary.RunnerTests',
  );
}
